### ISSUE TITLE
"React does not recognize the `gapMode` prop on a DOM element" warning

### ISSUE THREAD

**Issue by tpaan** [theKashey/react-focus-on#67]
After updating to `3.8.0` I am getting the following warning:

```
    Warning: React does not recognize the `gapMode` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `gapmode` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
        at div
        at /home/timo/Code/asti/my-app/node_modules/react-remove-scroll/dist/es5/UI.js:16:21
        at FocusLockUI (/home/timo/Code/asti/my-app/node_modules/react-focus-lock/dist/cjs/Lock.js:40:31)
        at /home/timo/Code/asti/my-app/node_modules/react-focus-on/dist/es5/UI.js:10:20
        at div
        at Modal (/home/timo/Code/asti/my-app/src/components/Modal/Modal.tsx:12:34)
```

**Comment by theKashey** [comment]
Related to #65

**Comment by kyeckeq** [comment]
I'm seeing same - v3.8.0.

**Comment by theKashey** [comment]
Yep, sorry forgot to post an update - version 3.8.1 resolves the problem.
